default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: 5
  socket: /var/lib/mysql/mysql.sock
  host: db

development:
  <<: *default
  database: SEMINARHP_development

test:
  <<: *default
  database: SEMINARHP_test
  