default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: SEMINARHP_development

test:
  <<: *default
  database: SEMINARHP_test
  