default: &default
  adapter: mysql2
  encoding: unicode
  username: root
  password: password
  pool: 5
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default
  database: SEMINARHP_development

test:
  <<: *default
  database: SEMINARHP_test
  