version: '3'
services:
  mysql:  # config/database.yml中のローカル環境のホスト名と揃える
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - '5000:3306' # 3306:3306だと上手く行かなかったので5000:3306とした
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: seminar_development  # ローカル環境のDB名
      MYSQL_USER: root                        # ローカル環境のDBを使用する時に使うユーザー名
      MYSQL_PASSWORD: password                # ローカル環境のDBを使用する時に使うパスワード
  app:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/MyApp
    ports:
      - "3000:3000"
    depends_on:
      - mysql
volumes:
  mysql-data:
    driver: localversion: '3'
